name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Set up ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
        architecture: 'x64'

    - name: Setup bundler
      run: gem install bundler -v 2.1.4 --no-doc

    - name: Setup gems
      run: bundle install --jobs 4
    
    - name: Yarn install
      run: yarn install --dev
    
    - name: ESLint
      run: yarn eslint --ext .js --ext .es6 assets/javascripts
    
    - name: Prettier
      run: |
        yarn prettier -v
        yarn prettier --list-different \
          "assets/stylesheets/**/*.scss" \
          "assets/javascripts/**/*.{js,es6}"
      
    - name: Rubocop
      run: bundle exec rubocop .
    
    - name: Autofix Failures
      if: ${{ failure() }}
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        rubocop: true
        rubocop_command_prefix: 'bundle exec'
        eslint: true
        prettier: true
        auto_fix: true
        git_email: 'ci@discourse'
